157182881 macos ci travis
emotiq/emotiq pull request #118
Opened 2018-04-30 10:51 UTC by echupriyanov

* CI
 * Support for LispWorks and CCL on both macOS and Linux
 * Build binaries for macOS and Linux using LispWorks
 * No upload to GitHub Releases yet
* Minor fixes to `emotiq` build script

2018-04-30 15:28 UTC, easye requested changes
0.  How tests are performed have unfortunately changed since you
    started on this trail.  Please see `dev` for how tests are
    invoked, and merge in the new machinery to this pull.

1.  Restore ability to test with `sbcl`.  

2.  See <https://twistapp.com/a/39362/ch/91845/t/316139/> to get other
    devloper "buyin" on changing the procedures.

3.  If we are going to move the C code to a separate repository, it
    should be removed from this repository.
    `etc/build-crypto-pairings.bash.paul` should be removed as well.

4.  Document how developers can make a new version of the external
    dependencies, and reference that version in these instructions.

2018-04-30 15:28 UTC, easye commented on ci/deps.lisp
> +(ql-dist:install-dist "http://beta.quicklisp.org/dist/quicklisp/2018-01-31/distinfo.txt" :replace t :prompt nil)
@echupriyanov This should not be done in the test environment, but rather be tested as part of the quickload process of each process.

2018-04-30 15:29 UTC, easye commented
(minor) The message about building libraries in src/Crypto/crypto-pairing.asd should be changed to inform the developer that the binaries are being downloaded from the network.

2018-05-02 15:31 UTC, easye commented
SBCL is not installing correctly under linux see <https://travis-ci.org/emotiq/emotiq/jobs/373974773#L800>

2018-05-02 15:47 UTC, easye requested changes
1.  The production images should end in `.tar.bz2` or `.tbz` to
    indicate that that are compressed archives.  They should unpack
    into a subdirectory named identically to the name before this
    extension.  Currently under, the tar has the name
    `emotiq-VERSION-macos` without extension, and unpacks in a
    directory `emtq-VERSION-macos`.  Just make this consistent.

2.  Make the `emotiq.bash` script executable with a 
    shebang line ```#!/usr/bin/env bash```.

3.  Any way to get a specific version for SBCL from the Brew install?
    Otherwise, we are going to diverge in the version of SBCL we test
    under Linux/macOS.

4.  Remove or rename `etc/build-crypto-pairings.bash.paul` depending
    on whether it is needed any longer.

5.  Need some basic documentation for developers to change the version
    of libraries referred to in `emotiq-external-libs`.

6.  The tarballs at `src/Crypto/PBC-Intfgmp-6.1.2.tar.bz2` and
    `src/Crypto/pbc-0.5.14.tar` should be removed.

2018-05-02 15:47 UTC, easye commented on .travis.yml
>  #
@echupriyanov Lines 64-66 should be deleted.

2018-05-02 15:47 UTC, easye commented on .travis.yml
>      - LISP=lispworks-bin
We should delete the commented out lines that will no longer work as we no longer are using Roswell.

Also, we should shorten the CCL to the simpler `ccl`.

2018-05-02 15:47 UTC, easye commented on etc/build-crypto-pairings.bash.paul
> +#!/usr/bin/env bash
@echupriyanov Do we need this file?  If so, please rename it to something to reflect its usage with an explanation, otherwise please delete.

2018-05-07 16:30 UTC, easye commented
@echupriyanov I have tested both the developer version and the  `production.bash` under Linux and macOS, and I think things are ready to go.  

We probably need to give a HEADSUP to other developers, as transitioning to the development version of the PBC library can cause slight confusion.  We simply need to inform developers that they should remove `<file:emotiq/var/>`, but still the errors when a developer doesn't do that can be confusing.

2018-05-07 16:31 UTC, easye approved these changes
Tested developer and production builds outside Travis CI under Linux/macOS. 

Developers should be given HEADSUP to remove `<file:emotiq/var/>` when these changes are merged into `dev`.

2018-05-07 16:32 UTC, echupriyanov commented
@easye Ok. I'll write an announcement tomorrow morning and hit the switch merging into `dev`

2018-05-08 10:07 UTC, merged