Dbm 0430a
emotiq/emotiq pull request #133
Opened 2018-05-08 17:33 UTC by dbmcclain

clean slate of system for start of generate-tree and reconstruct-tree. Can now generate-tree and then init-sim, and run successfully to completion.

2018-05-08 17:40 UTC, easye requested changes

2018-05-08 17:40 UTC, easye commented on src/Cosi-BLS/cosi-construction.lisp
> +(defvar *local-nodes*  '(("Arroyo.local"    . "127.0.0.1")))
@dbmcclain Let's change `Arroyo.local`  to `localhost` which would be meaningful to others than just your network.

2018-05-08 17:40 UTC, easye commented on src/Cosi-BLS/cosi-construction.lisp
> +        *leader-node* (get-local-ipv4 "Arroyo.local")
@dbmcclain Change to `localhost`?

2018-05-08 18:10 UTC, guitarvydas commented
CL-USER 5 > (cosi-simgen::generate-tree :nodes 3)
#<COSI-SIMGEN::NODE 40200108AB>

CL-USER 6 > (cosi-simgen::init-sim)
65001

CL-USER 7 > (cosi-simgen::tst-blk)
#<ACTORS:ACTOR 402004280B>

CL-USER 8 > cosi-simgen::*leader*
NIL

"Construct Genesis transaction" 
"Find UTX for Mary" 
"Construct 2nd transaction" 
:SENT-TO-NULL 
(:MAKE-BLOCK)

2018-05-09 12:59 UTC, easye commented
Good news: I figured out a way around the problems. They have nothing to do with setting specials, but rather if one calls cosi-simgen::shutdown-server without starting a server, there is no UDP traffic.

My simple fix on https://github.com/emotiq/emotiq/tree/dbm-0430a-mte is to put a simple numeric count around shutting down the server like https://github.com/emotiq/emotiq/commit/50cb1d1f70f63922879f45c44df7c8dd4ff7725f

2018-05-09 16:25 UTC, easye approved these changes

2018-05-09 16:26 UTC, merged