Pt sim election
emotiq/emotiq pull request #150
Opened 2018-05-11 14:29 UTC by guitarvydas

It appears that faked elections work.  I believe that there are enough comments in src/election.lisp and node-sim.lisp.

2018-05-11 14:34 UTC, easye requested changes

2018-05-11 14:34 UTC, easye commented on src/Cosi-BLS/cosi-handlers.lisp
> +#|
@guitarvydas Just go ahead and remove such references to a specific network configuration.

2018-05-11 14:34 UTC, easye commented on src/sim-election.lisp
> +    (setf *beacon-timer* (mp:make-timer (lambda ()
@guitarvydas We have to make the code work under `ccl` (and hopefully soon `sbcl`).  I think you should use the `mp-compat` system here to make a timer, or go find a suitable system in Quicklisp

2018-05-11 15:47 UTC, easye requested changes
1.  Elections are happening too fast for anything meaningful.  Please allow the configuration of the time between elections.

2.  Holding an election without sealing a block doesn't make sense.  When the election timer fires, the block should be sealed, then the election held.  As such, you should probably deprecate the `force 

3.  Please output the identity of the new leader after the election has occurred.

2018-05-11 15:47 UTC, easye commented on src/node-sim.lisp
> -  (setf cosi-simgen::*cosi-prepare-timeout* cosi-prepare-timeout)
@guitarvydas You've deleted the configuration options to set the Cosi timeouts.  Please reinstate, or explain why you deleted this option.

2018-05-12 04:35 UTC, dbmcclain commented
Elections should be run by all witness nodes. There is no need to broadcast the outcome of the leader election. If, perchance, two different nodes think they both won the election, only one - at most - can achieve BFT.

2018-05-14 21:12 UTC, closed without merging