Dbm 0519a
emotiq/emotiq pull request #160
Opened 2018-05-19 21:41 UTC by dbmcclain

merge with dev as of 21:38 UTC on May 19, 2018. Fix block validation to perform proper block hash checking between transactions and stored hash in block header, transaction validation, during Cosi PREPARE phase. 

Fix block header hash calculation to exclude block signature slots (sig, pkey, bitmap). 

Perform full multisignature validation, check that composite signing public key is crypto sum of witness keys as indicated in the signature bitmap, during Cosi COMMIT phase.

2018-05-21 17:53 UTC, dbmcclain commented
Fix node message dispatch to use CLOS method with EQL dispatch on first argument (typically, a symbol message name). Fix Emotiq/sim to conform to new dispatch mechanism. No need to override existing handlers, unless you want to. Cosi and Emotiq sim tests now function together without any clashes. 

Emotiq/sim tests on cloaked and uncloaked transactions runs okay now. Fixed election sim to likewise conform to new message dispatch.

Extended exports from cosi-simgen to alleviate references to private symbols in Emotiq sim.

2018-05-22 15:55 UTC, easye requested changes
Please resolve issues with @guitarvydas.

2018-05-22 15:55 UTC, easye commented on src/Cosi-BLS/cosi-netw-xlat.lisp
> +(defvar *machine-ip-addr* (comm:get-host-entry (machine-instance) :fields '(:address)))
@dbmcclain Referencing the LispWorks only `comm` package causes compilation to fail on other implementations.

2018-05-22 15:55 UTC, easye commented on src/Actors/actors-startup.lisp
> +#+(AND (NOT :COM.RAL)
@dbmcclain Why do we want to conditionalize on running on these Lisps?  Is this related to some need of the Actor code?  Shouldn't you just attempt to `install-actor-system` for all Lisps from this point, and let the `actor` system deal with whether it can run on a given implementation?

2018-05-22 15:55 UTC, easye commented on src/node-sim.lisp
> +  (let ((fee 10))
@dbmcclain If you are going to change what the function does and it has a docstring, you need to change the docstring to reflect the new behavior.

2018-05-22 15:55 UTC, easye commented on src/simulation.md
> +    (emotiq/sim::run)
@dbmcclain The symbol is exported, so no need to document calling the private symbol.

2018-05-22 15:55 UTC, easye commented on src/Cosi-BLS/range-proofs.lisp
> +  (make-bp-basis :CURVE :CURVE-E382
@dbmcclain Where are these constants coming from?

2018-05-22 19:39 UTC, dbmcclain commented on src/Actors/actors-startup.lisp
> +#+(AND (NOT :COM.RAL)
You may not want to conditionalize on Lisp variant. But for general purpose use, I need my copy of Lipspworks to use the ACTIONS system to fire up Actors. These Actors are used in my lab system for running lab equipment and need to get fired up at init time, but only after multiprocessing has started.

2018-05-22 19:41 UTC, dbmcclain commented on src/simulation.md
> +    (emotiq/sim::run)
I didn't touch this file. I don't know what its purpose is. I merely touched up Paul's sources to remove references to cosi-simgen internal symbols.

2018-05-22 19:42 UTC, dbmcclain commented on src/Cosi-BLS/range-proofs.lisp
> +  (make-bp-basis :CURVE :CURVE-E382
The constants are generated at genesis time (by me, in the source code) to establish basis vectors in the Elliptic curves for use in Bulletproofs. Lacking the pre-made basis vectors, we have the system auto-initialize, but that bites on every Bulletproof. If they pre-exist, then we save the time needed to generate the basis vectors in every call to MAKE-RANGE-PROOF.

2018-05-22 19:43 UTC, dbmcclain commented on src/Cosi-BLS/cosi-netw-xlat.lisp
> +(defvar *machine-ip-addr* (comm:get-host-entry (machine-instance) :fields '(:address)))
Yes, I understand. Perhaps our network experts know a better way? But at any rate this particular code disappears once I am fully hooked into Shannon's Gossip system.

2018-05-22 19:44 UTC, dbmcclain commented on src/node-sim.lisp
> +  (let ((fee 10))
I didn't change the semantics of anything, as far as I know, just syntactic substitutions.

2018-05-23 16:56 UTC, closed without merging