157484804 create websocket interface
emotiq/emotiq pull request #233
Opened 2018-06-19 12:07 UTC by easye

Commit to a wallet serialization strategy.  

REST/Websocket now use a separate model of the contents of the wallet.  Moved mock behavior into model in anticipation of revision.

2018-06-20 11:31 UTC, markhdavid requested changes
Given that the tests are failing and there's a fatal call to APPLY, I'll reject this for now.

2018-06-20 11:31 UTC, markhdavid commented on src/model/mock.lisp
> +               (apply notify-hook notification))
This cannot work: APPLY's last arg must be a list.

2018-06-20 11:31 UTC, markhdavid commented on src/model/mock.lisp
>    (let ((epoch (+ 1000 (random 10000)))
I do not understand what this is doing. Can you explain the concept here a bit? I see it goes into a forever loop, but I don't really get what's going on. Is "mock" a computer term other than to mean simulate or stub something?

2018-06-20 11:45 UTC, guitarvydas submitted a review, later dismissed
Runs my 3 tests OK.
I can't connect to ws://localhost:3145/, but that is probably OK, since I'm using a browser, not a websocket client.
I can connect to http://127.0.0.1:3140.
I see that MarkD commented as I was commenting.  I will defer to MarkD.

2018-06-20 11:48 UTC, guitarvydas reviewed
Runs my 3 tests OK.
I can't connect to ws://localhost:3145/, but that is probably OK, since I'm using a browser, not a websocket client.
I can connect to http://127.0.0.1:3140.
I see that MarkD commented as I was commenting. I will defer to MarkD.

2018-06-20 19:52 UTC, markhdavid commented
By "tests fail" I only meant CI tests fail. I would like to know how this is to be tested though.  I could defer to Paul on that if he knows how to test.

2018-06-22 13:02 UTC, easye commented
@guitarvydas (and possibly @markhdavid):

I have submitted patches to address your review comments on this branch.  Please review again for approval when you have a chance…

2018-06-25 20:53 UTC, markhdavid commented
Previously, the CI was not passing. Now I see the CI is passing.  Paul stated in a private message more than an hour ago that the CI is not passing. That is not true, in fact. Plus, he has not responded to questions seeking further explanation. Accordingly, in the interest of moving forward expeditiously, I will remove my objection, and approve this.

2018-06-25 20:53 UTC, markhdavid submitted a review, later dismissed

2018-06-25 21:19 UTC, guitarvydas commented
![screenshot 2018-06-25 17 17 31](https://user-images.githubusercontent.com/1690648/41876461-dfe5c45e-789b-11e8-9f35-15593891fead.png)

2018-07-02 16:33 UTC, easye commented
Closed in lieu of #278.

2018-07-02 16:33 UTC, closed without merging