Emotiq config purely local
emotiq/emotiq pull request #389
Opened 2018-07-30 13:37 UTC by easye

Implements #388 

An attempt to establish a baseline on `dev` that runs the work we did last week on replacing the simulator with a purely locally running chain within a single process.

Merges in David McClain's code for synchronizing blocks on rejoin (untested).

Mainly allows one to run `(emotiq/config/generate:ensure-defaults :force t :for-purely-local t)` to run the local node simulator from scratch.  

TODO: needs to be integrated with devops machinery for configuration changes.  (untested)

2018-07-30 14:22 UTC, dbmcclain commented
okay, cleared .cache, remove var/local, load up from scratch emotiq/startup, emotiq/txn, emotiq/config, emotiq/config/generate and then ran (emotiq/config/generate :force t :for-purely-local t). Seemed to run without surprises. (would be helpful for you to indicate needed load sequence).

Then ran (emotiq:main) - again without surprises. So appears to be working. Looks like you merged in the latest Cosi handlers and changes for running back-fill on new nodes joining. 

Seems like a go!

2018-07-30 14:23 UTC, dbmcclain approved these changes
Comments per general comments just made.

2018-07-30 14:27 UTC, echupriyanov requested changes
While it seems like its working to generate local network in single process, it fails to properly generate configs for several lisp processes on the same IP.
I have working config generator in `network-generate` branch, and, I think, its a good time to merge it in before we diverge too much.

2018-07-30 14:35 UTC, easye commented
> I have working config generator in network-generate branch, and, I think, its a good time to merge it in before we diverge too much.

@echupriyanov 

If you can merge here, fine.  This branch currently as the (deprecated) `emotiq/fs:*subpath*` disabled, so I think I also need to fix this on the Lisp side.

2018-07-30 14:43 UTC, echupriyanov commented
@easye This should be done on the Lisp side. I can work on this to let you focus on the other parts.

2018-07-30 14:43 UTC, easye commented
> This should be done on the Lisp side. I can work on this to let you focus on the other parts.

@echupriyanov Should be fixed in https://github.com/emotiq/emotiq/pull/389/commits/7d1836a220412f005c1b0a0978b39421f79628cd

2018-07-30 14:50 UTC, echupriyanov commented
@easye no, this doesn't fix config **generation**.
Try to gennerate config for following nodes:
```lisp
(
  (
    :hostname "127.0.0.1"
    :ip "127.0.0.1"
    :gossip-server-port 65000
    :rest-server-port 3140
    :websocket-server-port 4145
  )
  (
    :hostname "127.0.0.1"
    :ip "127.0.0.1"
    :gossip-server-port 65001
    :rest-server-port 3141
    :websocket-server-port 4146
  )
  (
    :hostname "127.0.0.1"
    :ip "127.0.0.1"
    :gossip-server-port 65002
    :rest-server-port 3142
    :websocket-server-port 4147
  )
  (
    :hostname "127.0.0.1"
    :ip "127.0.0.1"
    :gossip-server-port 65003
    :rest-server-port 3143
    :websocket-server-port 4148
  )
  (
    :hostname "127.0.0.1"
    :ip "127.0.0.1"
    :gossip-server-port 65004
    :rest-server-port 3144
    :websocket-server-port 4149
  )
  (
    :hostname "127.0.0.1"
    :ip "127.0.0.1"
    :gossip-server-port 65005
    :rest-server-port 3145
    :websocket-server-port 4150
  )
  (
    :hostname "127.0.0.1"
    :ip "127.0.0.1"
    :gossip-server-port 65006
    :rest-server-port 3146
    :websocket-server-port 4151
  )
  (
    :hostname "127.0.0.1"
    :ip "127.0.0.1"
    :gossip-server-port 65007
    :rest-server-port 3147
    :websocket-server-port 4152
  )
  (
    :hostname "127.0.0.1"
    :ip "127.0.0.1"
    :gossip-server-port 65008
    :rest-server-port 3148
    :websocket-server-port 4153
  )
  (
    :hostname "127.0.0.1"
    :ip "127.0.0.1"
    :gossip-server-port 65009
    :rest-server-port 3149
    :websocket-server-port 4154
  )
  (
    :hostname "127.0.0.1"
    :ip "127.0.0.1"
    :gossip-server-port 65010
    :rest-server-port 3150
    :websocket-server-port 4155
  )
  (
    :hostname "127.0.0.1"
    :ip "127.0.0.1"
    :gossip-server-port 65011
    :rest-server-port 3151
    :websocket-server-port 4156
  )
  (
    :hostname "127.0.0.1"
    :ip "127.0.0.1"
    :gossip-server-port 65012
    :rest-server-port 3152
    :websocket-server-port 4157
  )
)
```

2018-07-30 15:30 UTC, easye commented
> his doesn't fix config generation. Try to generate config for following nodes: […]

https://github.com/emotiq/emotiq/pull/389/commits/28df0aafe3d407ad859bff959d0ef0944b869928 adds this as failing test

2018-07-30 17:12 UTC, echupriyanov commented
Production path looks ok now (`~/Library/Application Support/Emotiq`). But:
* `emotiq-conf.json`, generated by `(emotiq/config/generate:ensure-defaults :force t :for-purely-local t)` doesn't look correct:
{"stakes":[[35287301068112264043976068996523041634604654302227397700850534735809039128972369452193122291095047880216319218650764179078649357274323137903777885876918001391855609789591062903042518036165659596993977662732480988815172752784375634296595332031042919601014395129539063631315456,334767],[27369299246091238982691700339011177080768650750301169580503821364806010283709242907086740701252584913292446110844154288668117696786704920930553540456457174529582689896043740727186867275681912947184737685366697563993756488665167989509340461840633792999827401797855708135494912,573685],[52987819497218215273448805689600199624576387780584671137876848181398767057748219589523710916028049392998864418290446659746302451477311290415844353347477522620834227676193845330796836579305754540671756070479699149928984143357971789132871719956462704703442237662546812841181953,405594]],"addressForCoins":35287301068112264043976068996523041634604654302227397700850534735809039128972369452193122291095047880216319218650764179078649357274323137903777885876918001391855609789591062903042518036165659596993977662732480988815172752784375634296595332031042919601014395129539063631315456,"private":1413691737078830334401078795474070089094228077460815003858236995123212860642163526973498275610094207799106674301410277089255626635365347,"public":52987819497218215273448805689600199624576387780584671137876848181398767057748219589523710916028049392998864418290446659746302451477311290415844353347477522620834227676193845330796836579305754540671756070479699149928984143357971789132871719956462704703442237662546812841181953,"ip":"10.178.15.71","hostname":"zt-emq-03.zt.emotiq.ch","hostname":"localhost","ip":"127.0.0.1","restServer":"true","restServerPort":3140,"websocketServer":"true","websocketServerPort":3145,"gossipServer":"true","gossipServerPort":65002,"genesisBlockFile":"emotiq-genesis-block.json"}


 Note duplicate `hostname` and `ip` fields.
* Running binary with configs generated by form above still fails:
```
Running interactively in production
with args [(/Users/eric/Copoka/Emotiq/emotiq/var/tmp/var/local/production/emotiq-20180730093855-4ad376c4-macos/emotiq)]

Error: NIL is not of type PBC-INTERFACE::FULL-CURVE-PARAMS when accessing slot PBC-INTERFACE::ZR-LEN.
  1 (abort) Quit process.

Type :b for backtrace or :c <option number> to proceed.
Type :bug-form "<subject>" for a bug report template or :? for other options.

```

But, maybe, these issues can go into separate PR?

2018-07-30 19:23 UTC, guitarvydas commented
@echupriyanov I think that I fixed the duplicated hostname and ip issue.  @easye the issue seems to be that PUSH can create duplicates - fixed by using remove-duplicates (and reverse'ing to ensure that the first item is kept)

2018-07-30 20:11 UTC, echupriyanov commented
@guitarvydas I was already fixing that in https://github.com/emotiq/emotiq/pull/309/commits/b44b9ba7f8b735ef3e81b9b6162b3c035df380f1

And there are more issues with config generation, also fixed in PR #309

2018-07-30 21:54 UTC, easye commented on src/filesystem.lisp
> +               #+:windows
@guitarvydas @echupriyanov @easye
Should use functional interfaces in `uiop:os-mumble` instead of compile time conditionals.

2018-07-30 21:57 UTC, easye commented on src/generate.lisp
> +     (remove-duplicates (reverse configuration) :test #'(lambda (x y) (eq (car x) (car y)))))))
@guitarvydas Need to ensure that last pushed items override previous items.

2018-07-31 10:51 UTC, easye commented on src/filesystem.lisp
> +               #+:windows
Fixed.

2018-07-31 10:51 UTC, easye commented on src/generate.lisp
> +     (remove-duplicates (reverse configuration) :test #'(lambda (x y) (eq (car x) (car y)))))))
Fixed.

2018-07-31 11:23 UTC, easye commented
I hope we are almost there.  

I think we just need to get `test-generate` to succeed on this branch.  

I see two outstanding problems:

1.    On the CI, something is different about assumptions about pathnames for the network-generation test

2.  genesis-create sometimes fails. Sometimes it succeeds.

2018-07-31 12:01 UTC, easye commented on src/genesis.lisp
> +  ;;; This is wrong:  use a special rather than the pathname
This comment is obsolete; it was addressed in this commit.

2018-07-31 12:24 UTC, echupriyanov approved these changes

2018-07-31 13:21 UTC, guitarvydas approved these changes

2018-07-31 13:22 UTC, merged