Fix ASDF definitions of crypto-pairings/t
emotiq/emotiq pull request #82
Opened 2018-04-11 15:34 UTC by easye

Do NOT add invoke ASDF:LOAD-SYSTEM machinery in file compilation
units.  Instead, encapsulate such relationships in the ASDF
definitions themselves.

2018-04-11 21:54 UTC, markhdavid commented
This gets an error on the second test. Please fix then resubmit.  Here's a copy/paste of the part of the log with the second test:


> The command "ros -e "(loop :for i :upfrom 1 :for (system dependencies) :in '((:crypto-pairings :crypto-pairings/t)) :doing (ql:quickload dependencies) :unless (asdf:test-system system) :return (uiop:quit (ash -1 i)) :finally (uiop:quit 0))"" exited with 0.
> $ ros -e "(loop :for i :upfrom 2 :for (system dependencies) :in '((:core-crypto :core-crypto)) ; no test system, so system itself :doing (ql:quickload dependencies) :unless (asdf:test-system system) :return (uiop:quit (ash -1 i)) :finally (uiop:quit 0))"
> ; Loading text file /home/travis/.roswell/impls/x86-64/linux/lispworks-bin/7.1.0.0/lib/7-1-0-0/private-patches/load.lisp
> LispWorks(R): The Common Lisp Programming Environment
> Copyright (C) 1987-2017 LispWorks Ltd.  All rights reserved.
> Version 7.1.0
> Saved by vagrant as lw-console, at 23 Mar 2018 7:03
> User travis on travis-job-3382fb17-0116-4939-a36b-06f7d71777de
> ; Loading /home/vagrant/.roswell/impls/x86-64/linux/lispworks-bin/7.1.0.0/lib/7-1-0-0/load-on-demand/utilities/asdf.64ufasl on demand...
> ; Loading text file /home/travis/.roswell/etc/roswell/init.lisp
> Warning: Using DEFPACKAGE to modify #<The QL-SETUP package, 25/32 internal, 3/16 external>.
> ; Loading /home/vagrant/.roswell/impls/x86-64/linux/lispworks-bin/7.1.0.0/lib/7-1-0-0/load-on-demand/processes/comm-defsys.lisp on demand...
> ;; Creating system "COMM"
> ; Loading /home/vagrant/.roswell/impls/x86-64/linux/lispworks-bin/7.1.0.0/lib/7-1-0-0/load-on-demand/ccl/describe.64ufasl on demand...
> ; Loading /home/vagrant/.roswell/impls/x86-64/linux/lispworks-bin/7.1.0.0/lib/7-1-0-0/load-on-demand/ccl/inspector-values.64ufasl on demand...
> ; Loading /home/vagrant/.roswell/impls/x86-64/linux/lispworks-bin/7.1.0.0/lib/7-1-0-0/load-on-demand/ffi/types/inspector.64ufasl on demand...
> ;  Loading text file /home/travis/.roswell/lisp/quicklisp/local-init/roswell.lisp
> ;   Loading text file /home/travis/.roswell/etc/roswell/patch-quicklisp.lisp
> ;    Loading text file /home/travis/.roswell/etc/roswell/util.lisp
> ;    Loading text file /home/travis/.roswell/etc/roswell/extend-quicklisp-system.lisp
> Error: End of file while reading stream #<SYSTEM::STRING-INPUT-STREAM 41208E4EDB>.
>   1 (abort) Abort initialization.
>   2 Continue to top-level loop.
> Type :b for backtrace or :c <option number> to proceed.
> Type :bug-form "<subject>" for a bug report template or :? for other options.
> CL-USER 1 : 1 >

2018-04-11 21:55 UTC, markhdavid requested changes
See recent message. CI build gets errors. Please fix.

2018-04-12 00:23 UTC, easye commented
@markhdavid The `.travis.yml.` ros invocations cannot use Lisp comments.

2018-04-12 18:41 UTC, markhdavid approved these changes

2018-04-12 18:44 UTC, merged